---
title: "HW 03"
author: "Lucas Smith"
format:
  html:
    embed-resources: true
toc: true
---

```{r}
pkgs = c("tidyverse", "grid", "gridExtra", "ggplot2", "reshape")
for (pkg in pkgs) {
  if (!require(pkg, character.only=TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}
```

## 1 - Du Bois challenge.

```{r}
#| label: label-me-1

dubois <- read_csv("data/income.csv")
db <- pivot_longer(dubois, 
                   c("Rent", "Food", "Clothes", "Tax", "Other"), 
                   names_to="income_type", values_to = "percent")
order <- rev(c("$100-200", "$200-300", "$300-400", "$400-500", "$500-750", "$750-1000", "$1000 AND OVER"))
x_ordering <- c("Rent", "Food", "Clothes", "Tax", "Other")
# might work ggplot(db, aes(x=factor(percent, levels=x_ordering), y=Class, fill=income_type)) +  geom_col(position="fill") + 


plt <- ggplot(db, aes(x=percent, y=Class, fill=income_type)) +  geom_col(position="fill") 
```

```{r}
tabledata <- dubois |> select(Class, Average_Income)
tab = tableGrob(tabledata, rows=NULL, theme=ttheme_minimal(base_size = 7))
tab$heights <- unit(rep(1/nrow(tab), nrow(tab)), "npc")

grid.arrange(
  arrangeGrob(tab),
  arrangeGrob(nullGrob(), plt + guides(fill=FALSE) + 
                       theme(axis.text.x=element_blank(),
                             axis.title.x=element_blank(),
                             axis.ticks.x=element_blank(), legend.position = NULL) + labs(x="", y=""), 
              heights=c(1, 9)),
  widths=c(2, 8)
)

```

```{}
```

## 2 - COVID survey - interpret

```{r}
#| label: label-me-2

```

## 3 - COVID survey - reconstruct

## 4 - COVID survey - re-reconstruct

## 5 - COVID survey - another view
